### ISSUE TITLE
Send time via UART in seconds (epoch format)

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/pira-smart-firmware#5]
Send time via UART in seconds (epoch format)

**Comment by gorankecman** [comment]
Now, time is sent in epoch format through UART. 
Branch: develop
SHA1: abd2d72be16ca2c2487ed12f21d6c2476c810053

@SloMusti Test after hex is provided and close the issue if resolved.

**Comment by SloMusti** [comment]
@gorankecman time is correct
